# Generated by Django 5.2.12 on 2026-03-28 07:08

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_menuitem_barcode_menuitem_reorder_level_and_more'),
        ('pos', '0002_orderline_tax_amount_alter_orderline_line_total_and_more'),
        ('tenants', '0002_alter_outlet_outlet_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_change', models.DecimalField(decimal_places=3, help_text='Positive adds stock; negative removes (e.g. sale).', max_digits=14)),
                ('reason', models.CharField(choices=[('receive', 'Receive / purchase'), ('sale', 'Sale (POS)'), ('adjust_in', 'Adjustment increase'), ('adjust_out', 'Adjustment decrease'), ('waste', 'Waste / shrink')], max_length=16)),
                ('note', models.CharField(blank=True, max_length=512)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='catalog.menuitem')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='pos.order')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='tenants.outlet')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='catalog.menuitem')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='tenants.outlet')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='tenants.tenant')),
            ],
            options={
                'ordering': ['outlet', 'menu_item__name'],
                'unique_together': {('outlet', 'menu_item')},
            },
        ),
    ]
