# Generated by Django 5.2.12 on 2026-03-28 07:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_menuitem_barcode_menuitem_reorder_level_and_more'),
        ('inventory', '0001_initial'),
        ('tenants', '0002_alter_outlet_outlet_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='transfer_batch',
            field=models.UUIDField(blank=True, db_index=True, help_text='Links paired transfer_out / transfer_in rows.', null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('receive', 'Receive / purchase'), ('sale', 'Sale (POS)'), ('adjust_in', 'Adjustment increase'), ('adjust_out', 'Adjustment decrease'), ('waste', 'Waste / shrink'), ('transfer_out', 'Transfer out'), ('transfer_in', 'Transfer in'), ('physical_count', 'Physical count adjustment')], max_length=16),
        ),
        migrations.CreateModel(
            name='StockCountSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('note', models.CharField(blank=True, max_length=512)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_count_sessions', to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_count_sessions', to='tenants.outlet')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_count_sessions', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockCountLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('counted_quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('system_quantity_before', models.DecimalField(decimal_places=3, max_digits=14)),
                ('variance', models.DecimalField(decimal_places=3, max_digits=14)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_count_lines', to='catalog.menuitem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockcountsession')),
            ],
            options={
                'ordering': ['menu_item__name'],
                'unique_together': {('session', 'menu_item')},
            },
        ),
    ]
