# Generated by Django 4.2.29 on 2026-03-28 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
        ('inventory', '0002_stockmovement_transfer_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='purchasing.purchaseorder'),
        ),
    ]
