# Generated by Django 5.2.12 on 2026-03-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockmovement_purchase_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('receive', 'Receive / purchase'), ('sale', 'Sale (POS)'), ('adjust_in', 'Adjustment increase'), ('adjust_out', 'Adjustment decrease'), ('waste', 'Waste / shrink'), ('transfer_out', 'Transfer out'), ('transfer_in', 'Transfer in'), ('physical_count', 'Physical count adjustment'), ('recipe', 'Recipe / BOM consumption')], max_length=16),
        ),
    ]
