# Generated by Django 5.2.12 on 2026-03-28 14:04

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_postgres_row_level_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSpace',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.PositiveIntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_spaces', to='tenants.site')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_spaces', to='tenants.tenant')),
            ],
            options={
                'ordering': ['site', 'name'],
                'unique_together': {('site', 'name')},
            },
        ),
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=32)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('tentative', 'Tentative'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='tentative', max_length=16)),
                ('headcount', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.TextField(blank=True)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_bookings', to='tenants.tenant')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='events.eventspace')),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
    ]
