# Generated by Django 5.2.13 on 2026-05-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('tenants', '0014_extend_rls_catalog_modifiers'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='eventbooking',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='events_booking_end_after_start'),
        ),
    ]
