# Generated by Django 5.2.17 on 2026-09-30 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('events', '0002_eventbooking_events_booking_end_after_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_bookings', to='customers.customer'),
        ),
    ]
