# Generated by Django 5.2.17 on 2026-09-30 14:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('tenants', '0015_tenantsettings_efris_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_variance_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('refund_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('lookback_days', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exception_policy', to='tenants.tenant')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('cash_variance_threshold__gte', 0), ('lookback_days__gte', 1), ('lookback_days__lte', 365), ('refund_threshold__gte', 0)), name='valid_exception_policy')],
            },
        ),
        migrations.CreateModel(
            name='ExceptionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=32)),
                ('entity_id', models.CharField(max_length=64)),
                ('fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed')], default='open', max_length=16)),
                ('note', models.CharField(max_length=1000)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exception_reviews', to='tenants.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'kind', 'entity_id', 'fingerprint'), name='unique_exception_review_version')],
            },
        ),
    ]
