# Generated by Django 5.2.17 on 2026-09-30 15:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_exception_rls'),
        ('tenants', '0015_tenantsettings_efris_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exceptionpolicy',
            name='discount_threshold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='exceptionpolicy',
            name='offline_age_hours',
            field=models.PositiveSmallIntegerField(default=24, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)]),
        ),
        migrations.AddField(
            model_name='exceptionpolicy',
            name='pin_failure_threshold',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='exceptionpolicy',
            name='stock_adjustment_threshold',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='exceptionreview',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_exception_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exceptionreview',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceptionreview',
            name='scope_outlet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenants.outlet'),
        ),
        migrations.AddField(
            model_name='exceptionreview',
            name='scope_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenants.site'),
        ),
        migrations.AddField(
            model_name='exceptionreview',
            name='source_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='exceptionreview',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('follow_up', 'Follow up'), ('resolved', 'Resolved review')], default='open', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='exceptionpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('discount_threshold__gte', 0), ('offline_age_hours__gte', 1), ('offline_age_hours__lte', 168), ('pin_failure_threshold__gte', 1), ('pin_failure_threshold__lte', 5), ('stock_adjustment_threshold__gte', 0)), name='valid_exception_extra_policy'),
        ),
    ]
