# Generated by Django 5.2.13 on 2026-05-05 13:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial_cashbook'),
        ('tenants', '0014_extend_rls_catalog_modifiers'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancePostingLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('pos_payment', 'POS payment'), ('purchase_receive_movement', 'Purchase receive movement')], max_length=48)),
                ('source_id', models.CharField(max_length=64)),
                ('cashbook_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='posting_link', to='finance.cashbookentry')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_posting_links', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'source_type', 'source_id'), name='uniq_finance_posting_source_per_tenant')],
            },
        ),
    ]
