# Generated by Django 5.2.17 on 2026-09-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_financepostinglink_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financepostinglink',
            name='source_type',
            field=models.CharField(choices=[('pos_payment', 'POS payment'), ('pos_refund', 'POS refund'), ('folio_payment', 'Folio payment'), ('purchase_receive_movement', 'Purchase receive movement'), ('supplier_payment', 'Supplier payment')], max_length=48),
        ),
    ]
