# Generated by Django 5.2.12 on 2026-03-28 07:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='tax_rate_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If set, tax is computed on the line subtotal (exclusive).', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
