# Generated by Django 5.2.12 on 2026-03-28 07:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_menuitem_tax_rate_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='Scannable barcode / PLU for retail and supermarket POS.', max_length=64),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='reorder_level',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Optional low-stock hint for dashboards (same UoM as quantity).', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='track_inventory',
            field=models.BooleanField(default=False, help_text='When true, outlet stock is reduced when the order is paid.'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='unit_of_measure',
            field=models.CharField(choices=[('each', 'Each (SKU / piece)'), ('kg', 'Kilogram'), ('lb', 'Pound'), ('liter', 'Liter')], default='each', max_length=16),
        ),
    ]
