# Generated by Django 5.2.12 on 2026-03-28 14:04

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_menuitem_barcode_menuitem_reorder_level_and_more'),
        ('tenants', '0003_postgres_row_level_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='consume_recipe_on_sale',
            field=models.BooleanField(default=False, help_text='When true and the order is fully paid, deduct recipe ingredient stock.'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='kds_station',
            field=models.CharField(blank=True, help_text='Default kitchen display station tag (e.g. kitchen, bar).', max_length=32),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_order_subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('outlets', models.ManyToManyField(blank=True, help_text='Empty = valid at all outlets.', related_name='promotions', to='tenants.outlet')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-starts_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItemRecipeLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_per_unit', models.DecimalField(decimal_places=3, help_text='Ingredient quantity consumed per 1 unit of parent sold.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('ingredient_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_recipes', to='catalog.menuitem')),
                ('parent_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_lines', to='catalog.menuitem')),
            ],
            options={
                'ordering': ['parent_item', 'ingredient_item__name'],
                'unique_together': {('parent_item', 'ingredient_item')},
            },
        ),
    ]
