# Generated by Django 5.2.12 on 2026-04-04 06:27

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_serviceofferingoption'),
        ('tenants', '0013_tenantsettings_business_lines'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifierGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('min_selections', models.PositiveSmallIntegerField(default=0, help_text='Minimum options the guest must pick from this group (0 = optional).')),
                ('max_selections', models.PositiveSmallIntegerField(blank=True, help_text='Maximum picks; blank = no limit.', null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_groups', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MenuItemModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_group_links', to='catalog.menuitem')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_links', to='catalog.modifiergroup')),
            ],
            options={
                'ordering': ['menu_item', 'sort_order', 'group__name'],
                'unique_together': {('menu_item', 'group')},
            },
        ),
        migrations.CreateModel(
            name='ModifierOption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('price_delta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Added to each unit's price before tax (per sold unit).", max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.modifiergroup')),
            ],
            options={
                'ordering': ['group', 'sort_order', 'name'],
                'unique_together': {('group', 'name')},
            },
        ),
    ]
