# Generated by Django 5.2.17 on 2026-10-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_modifiers_and_line_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='availability_note',
            field=models.CharField(blank=True, help_text="Optional short guest-facing availability note, such as 'Available until 4 PM'.", max_length=160),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='display_image_url',
            field=models.URLField(blank=True, help_text='Optional public image URL used on guest-facing and Service TV displays.'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Include this item in rotating Service TV menu highlights.'),
        ),
    ]
