# Generated by Django 5.2.12 on 2026-03-28 14:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tenants', '0003_postgres_row_level_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInvite',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('tenant_admin', 'Tenant admin'), ('site_manager', 'Site manager'), ('outlet_manager', 'Outlet manager'), ('front_desk', 'Front desk'), ('server', 'Server / floor'), ('bartender', 'Bartender'), ('kitchen', 'Kitchen'), ('storekeeper', 'Storekeeper'), ('accountant', 'Accountant (read-only)')], max_length=32)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites_sent', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_invites', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
