# Generated by Django 5.2.17 on 2026-09-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='staff_pin_failures',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='staff_pin_hash',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='membership',
            name='staff_pin_locked_until',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
