# Generated by Django 5.2.17 on 2026-10-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userinvite_scope'),
        ('tenants', '0016_alter_outlet_outlet_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='outlets',
            field=models.ManyToManyField(blank=True, help_text='When outlets are assigned, access is limited to those outlets. Empty means all permitted outlets under assigned sites.', related_name='memberships', to='tenants.outlet'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('tenant_admin', 'Tenant admin'), ('site_manager', 'Site manager'), ('outlet_manager', 'Outlet manager'), ('front_desk', 'Front desk'), ('server', 'Server / floor'), ('bartender', 'Bartender'), ('kitchen', 'Kitchen'), ('storekeeper', 'Storekeeper'), ('accountant', 'Accountant (read-only)'), ('cleaner', 'Housekeeping')], max_length=32),
        ),
        migrations.AlterField(
            model_name='membership',
            name='sites',
            field=models.ManyToManyField(blank=True, help_text='Workers must be assigned one or more sites. Empty means no site access.', related_name='memberships', to='tenants.site'),
        ),
        migrations.AlterField(
            model_name='userinvite',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('tenant_admin', 'Tenant admin'), ('site_manager', 'Site manager'), ('outlet_manager', 'Outlet manager'), ('front_desk', 'Front desk'), ('server', 'Server / floor'), ('bartender', 'Bartender'), ('kitchen', 'Kitchen'), ('storekeeper', 'Storekeeper'), ('accountant', 'Accountant (read-only)'), ('cleaner', 'Housekeeping')], max_length=32),
        ),
    ]
