# Generated by Django 5.2.12 on 2026-10-05 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_membership_staff_pin_failures_and_more'),
        ('accounts', '0004_alter_membership_outlets_alter_membership_role_and_more'),
    ]

    operations = [
    ]
