# Generated by Django 5.2.17 on 2026-09-29 12:28

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_purchasereceipt_rls'),
        ('tenants', '0015_tenantsettings_efris_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank transfer'), ('mobile_money', 'Mobile money'), ('card', 'Card'), ('other', 'Other')], max_length=24)),
                ('reference', models.CharField(blank=True, max_length=128)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='purchasing.purchaseorder')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payments_recorded', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_payments', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='uniq_supplier_payment_key_tenant')],
            },
        ),
    ]
