# Generated by Django 5.2.17 on 2026-09-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0005_supplierpayment_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereceipt',
            name='discrepancy_note',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
