# Generated by Django 5.2.12 on 2026-03-28 14:04

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0002_folio_folioline'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomRateWindow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=128)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, help_text='Null = open-ended from valid_from.', null=True)),
                ('nightly_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_windows', to='lodging.roomtype')),
            ],
            options={
                'ordering': ['room_type', 'valid_from'],
                'constraints': [models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='lodging_roomratewindow_valid_range')],
            },
        ),
    ]
