# Generated by Django 5.2.13 on 2026-05-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0003_roomratewindow'),
        ('tenants', '0014_extend_rls_catalog_modifiers'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('check_out__gt', models.F('check_in'))), name='lodging_reservation_check_out_after_check_in'),
        ),
    ]
