# Generated by Django 5.2.17 on 2026-09-30 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('lodging', '0008_roommaintenancerequest_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='folio',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='folios', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='customers.customer'),
        ),
    ]
