from django.urls import path

from . import views, views_catalog, views_org, views_platform, views_rates

urlpatterns = [
    path("", views.ConsoleIndexView.as_view(), name="console-index"),
    path("select-tenant/", views.ConsoleSelectTenantView.as_view(), name="console-select-tenant"),
    path(
        "platform/tenants/",
        views_platform.PlatformTenantListView.as_view(),
        name="console-platform-tenants",
    ),
    path(
        "platform/tenants/new/",
        views_platform.PlatformTenantCreateView.as_view(),
        name="console-platform-tenant-create",
    ),
    path(
        "platform/tenants/<uuid:tenant_id>/edit/",
        views_platform.PlatformTenantUpdateView.as_view(),
        name="console-platform-tenant-edit",
    ),
    path(
        "platform/tenants/<uuid:tenant_id>/control-plane/",
        views_platform.PlatformTenantControlPlaneView.as_view(),
        name="console-platform-tenant-control-plane",
    ),
    path(
        "platform/plans/",
        views_platform.PlatformPlanListView.as_view(),
        name="console-platform-plans",
    ),
    path(
        "platform/plans/new/",
        views_platform.PlatformPlanCreateView.as_view(),
        name="console-platform-plan-create",
    ),
    path(
        "platform/plans/<int:plan_id>/edit/",
        views_platform.PlatformPlanUpdateView.as_view(),
        name="console-platform-plan-edit",
    ),
    path("org/", views_org.OrgOverviewView.as_view(), name="console-org"),
    path("org/setup/", views_org.OrgSetupWizardView.as_view(), name="console-org-setup"),
    path("org/setup/step-state/", views_org.OrgSetupStepStateView.as_view(), name="console-org-setup-step-state"),
    path("org/sites/", views_org.OrgSiteListView.as_view(), name="console-org-sites"),
    path("org/sites/new/", views_org.OrgSiteCreateView.as_view(), name="console-org-site-create"),
    path(
        "org/sites/<uuid:site_id>/edit/",
        views_org.OrgSiteUpdateView.as_view(),
        name="console-org-site-edit",
    ),
    path(
        "org/sites/<uuid:site_id>/outlets/",
        views_org.OrgOutletListView.as_view(),
        name="console-org-outlets",
    ),
    path(
        "org/sites/<uuid:site_id>/outlets/new/",
        views_org.OrgOutletCreateView.as_view(),
        name="console-org-outlet-create",
    ),
    path(
        "org/outlets/<uuid:outlet_id>/edit/",
        views_org.OrgOutletUpdateView.as_view(),
        name="console-org-outlet-edit",
    ),
    path(
        "org/lodging/room-types/",
        views_org.OrgRoomTypeListView.as_view(),
        name="console-org-room-types",
    ),
    path(
        "org/lodging/room-types/new/",
        views_org.OrgRoomTypeCreateView.as_view(),
        name="console-org-room-type-create",
    ),
    path(
        "org/lodging/room-types/<uuid:room_type_id>/edit/",
        views_org.OrgRoomTypeUpdateView.as_view(),
        name="console-org-room-type-edit",
    ),
    path(
        "org/lodging/rooms/",
        views_org.OrgRoomListView.as_view(),
        name="console-org-rooms",
    ),
    path(
        "org/lodging/rooms/new/",
        views_org.OrgRoomCreateView.as_view(),
        name="console-org-room-create",
    ),
    path(
        "org/lodging/rooms/<uuid:room_id>/edit/",
        views_org.OrgRoomUpdateView.as_view(),
        name="console-org-room-edit",
    ),
    path(
        "org/lodging/rates/",
        views_rates.OrgRoomRateWindowListView.as_view(),
        name="console-org-room-rates",
    ),
    path(
        "org/lodging/rates/new/",
        views_rates.OrgRoomRateWindowCreateView.as_view(),
        name="console-org-room-rate-create",
    ),
    path(
        "org/lodging/rates/<uuid:rate_id>/edit/",
        views_rates.OrgRoomRateWindowUpdateView.as_view(),
        name="console-org-room-rate-edit",
    ),
    path(
        "org/menu/modifier-groups/",
        views_catalog.OrgModifierGroupListView.as_view(),
        name="console-org-modifier-groups",
    ),
    path(
        "org/menu/modifier-groups/new/",
        views_catalog.OrgModifierGroupCreateView.as_view(),
        name="console-org-modifier-group-create",
    ),
    path(
        "org/menu/modifier-groups/<uuid:group_id>/edit/",
        views_catalog.OrgModifierGroupUpdateView.as_view(),
        name="console-org-modifier-group-edit",
    ),
    path(
        "org/menu/modifier-groups/<uuid:group_id>/options/",
        views_catalog.OrgModifierOptionListView.as_view(),
        name="console-org-modifier-options",
    ),
    path(
        "org/menu/modifier-groups/<uuid:group_id>/options/new/",
        views_catalog.OrgModifierOptionCreateView.as_view(),
        name="console-org-modifier-option-create",
    ),
    path(
        "org/menu/modifier-groups/<uuid:group_id>/options/<uuid:option_id>/edit/",
        views_catalog.OrgModifierOptionUpdateView.as_view(),
        name="console-org-modifier-option-edit",
    ),
    path(
        "org/menu/categories/",
        views_catalog.OrgMenuCategoryListView.as_view(),
        name="console-org-menu-categories",
    ),
    path(
        "org/menu/categories/new/",
        views_catalog.OrgMenuCategoryCreateView.as_view(),
        name="console-org-menu-category-create",
    ),
    path(
        "org/menu/categories/<uuid:category_id>/edit/",
        views_catalog.OrgMenuCategoryUpdateView.as_view(),
        name="console-org-menu-category-edit",
    ),
    path(
        "org/menu/items/",
        views_catalog.OrgMenuItemListView.as_view(),
        name="console-org-menu-items",
    ),
    path(
        "org/menu/items/new/",
        views_catalog.OrgMenuItemCreateView.as_view(),
        name="console-org-menu-item-create",
    ),
    path(
        "org/menu/items/<uuid:item_id>/edit/",
        views_catalog.OrgMenuItemUpdateView.as_view(),
        name="console-org-menu-item-edit",
    ),
    path(
        "org/menu/items/<uuid:item_id>/outlets/",
        views_catalog.OrgMenuItemOutletListView.as_view(),
        name="console-org-menu-item-outlets",
    ),
    path(
        "org/menu/items/<uuid:item_id>/outlets/new/",
        views_catalog.OrgMenuItemOutletCreateView.as_view(),
        name="console-org-menu-item-outlet-create",
    ),
    path(
        "org/menu/items/<uuid:item_id>/outlets/<int:link_id>/edit/",
        views_catalog.OrgMenuItemOutletUpdateView.as_view(),
        name="console-org-menu-item-outlet-edit",
    ),
    path(
        "org/menu/items/<uuid:item_id>/outlets/<int:link_id>/delete/",
        views_catalog.OrgMenuItemOutletDeleteView.as_view(),
        name="console-org-menu-item-outlet-delete",
    ),
    path(
        "org/menu/items/<uuid:item_id>/recipe/",
        views_catalog.OrgMenuItemRecipeListView.as_view(),
        name="console-org-menu-item-recipe",
    ),
    path(
        "org/menu/items/<uuid:item_id>/recipe/new/",
        views_catalog.OrgMenuItemRecipeCreateView.as_view(),
        name="console-org-menu-item-recipe-create",
    ),
    path(
        "org/menu/items/<uuid:item_id>/recipe/<uuid:line_id>/edit/",
        views_catalog.OrgMenuItemRecipeUpdateView.as_view(),
        name="console-org-menu-item-recipe-edit",
    ),
    path(
        "org/menu/items/<uuid:item_id>/recipe/<uuid:line_id>/delete/",
        views_catalog.OrgMenuItemRecipeDeleteView.as_view(),
        name="console-org-menu-item-recipe-delete",
    ),
    path(
        "org/services/",
        views_catalog.OrgServiceOfferingListView.as_view(),
        name="console-org-service-offerings",
    ),
    path(
        "org/services/new/",
        views_catalog.OrgServiceOfferingCreateView.as_view(),
        name="console-org-service-offering-create",
    ),
    path(
        "org/services/<uuid:service_id>/edit/",
        views_catalog.OrgServiceOfferingUpdateView.as_view(),
        name="console-org-service-offering-edit",
    ),
    path(
        "org/services/<uuid:service_id>/packages/",
        views_catalog.OrgServiceOfferingOptionListView.as_view(),
        name="console-org-service-offering-options",
    ),
    path(
        "org/services/<uuid:service_id>/packages/new/",
        views_catalog.OrgServiceOfferingOptionCreateView.as_view(),
        name="console-org-service-offering-option-create",
    ),
    path(
        "org/services/<uuid:service_id>/packages/<uuid:option_id>/edit/",
        views_catalog.OrgServiceOfferingOptionUpdateView.as_view(),
        name="console-org-service-offering-option-edit",
    ),
]
