# Generated by Django 5.2.12 on 2026-03-28 14:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_postgres_row_level_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_key', models.CharField(help_text='Stable key e.g. stripe_connect, mailchimp, sms_gateway.', max_length=64)),
                ('label', models.CharField(blank=True, max_length=128)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('is_enabled', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_links', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant', 'provider_key'],
                'unique_together': {('tenant', 'provider_key')},
            },
        ),
    ]
