# Generated by Django 5.2.13 on 2026-05-05 14:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_financepostinglink'),
        ('integrations', '0001_initial'),
        ('tenants', '0015_tenantsettings_efris_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='EfrisSubmission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('submitted', 'Submitted'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('provider_reference', models.CharField(blank=True, max_length=128)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('cashbook_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='efris_submission', to='finance.cashbookentry')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efris_submissions', to='tenants.tenant')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
