# Generated by Django 5.2.12 on 2026-03-28 06:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address_line', models.CharField(blank=True, max_length=512)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant', 'name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_currency', models.CharField(default='USD', max_length=3)),
                ('default_timezone', models.CharField(default='UTC', max_length=64)),
                ('receipt_footer', models.TextField(blank=True)),
                ('theme_primary', models.CharField(default='#E85D4C', help_text='Hex color', max_length=7)),
                ('theme_secondary', models.CharField(default='#2DD4BF', help_text='Hex color', max_length=7)),
                ('theme_accent', models.CharField(default='#FBBF24', help_text='Hex color', max_length=7)),
                ('logo_url', models.URLField(blank=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('outlet_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('bar', 'Bar'), ('lounge', 'Lounge'), ('cafeteria', 'Cafeteria'), ('lodging_front_desk', 'Lodging / front desk'), ('retail', 'Retail'), ('event_space', 'Event space')], default='restaurant', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlets', to='tenants.site')),
            ],
            options={
                'ordering': ['site', 'name'],
                'unique_together': {('site', 'name')},
            },
        ),
    ]
