# Generated by Django 5.2.12 on 2026-03-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='outlet_type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('bar', 'Bar'), ('lounge', 'Lounge'), ('cafeteria', 'Cafeteria'), ('lodging_front_desk', 'Lodging / front desk'), ('retail', 'Retail / shop'), ('supermarket', 'Supermarket / grocery'), ('event_space', 'Event space')], default='restaurant', max_length=32),
        ),
    ]
