# Generated by Django 5.2.12 on 2026-03-29 08:55

import apps.tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenantsettings_enabled_staff_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantsettings',
            name='enabled_staff_modules',
            field=models.JSONField(default=apps.tenants.models.default_enabled_staff_modules, help_text='Staff UI modules this tenant subscribes to. Keys: pos, kitchen, promotions, inventory, purchasing, lodging, events, workspace.'),
        ),
    ]
