# Generated by Django 5.2.13 on 2026-05-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_extend_rls_catalog_modifiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='efris_enabled',
            field=models.BooleanField(default=False, help_text='If enabled, finance postings are queued for Uganda EFRIS submission. Keep off for properties that do not use EFRIS.'),
        ),
    ]
