# Generated by Django 5.2.16 on 2026-09-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_tenantsettings_efris_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='outlet_type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('bar', 'Bar'), ('lounge', 'Lounge'), ('cafeteria', 'Cafeteria'), ('lodging_front_desk', 'Lodging / front desk'), ('retail', 'Retail / shop'), ('supermarket', 'Supermarket / grocery'), ('event_space', 'Event space'), ('service', 'Services / appointments')], default='restaurant', max_length=32),
        ),
        migrations.AlterField(
            model_name='tenantoutletmodulepolicy',
            name='outlet_type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('bar', 'Bar'), ('lounge', 'Lounge'), ('cafeteria', 'Cafeteria'), ('lodging_front_desk', 'Lodging / front desk'), ('retail', 'Retail / shop'), ('supermarket', 'Supermarket / grocery'), ('event_space', 'Event space'), ('service', 'Services / appointments')], max_length=32),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='business_lines',
            field=models.JSONField(default=list, help_text='Business lines enabled for this workspace. Keys: bar, lounge, restaurant, cafeteria, kitchen, lodging, retail, supermarket, events, services.'),
        ),
    ]
