# Generated by Django 5.2.17 on 2026-10-06 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0016_alter_outlet_outlet_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hostname', models.CharField(max_length=253, unique=True)),
                ('kind', models.CharField(choices=[('platform', 'Platform subdomain'), ('custom', 'Custom domain')], max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pending verification'), ('verified', 'Verified'), ('active', 'Active'), ('disabled', 'Disabled')], default='pending', max_length=12)),
                ('is_primary', models.BooleanField(default=False)),
                ('verification_token', models.CharField(blank=True, max_length=64)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('tls_status', models.CharField(default='not_configured', max_length=24)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant__name', 'hostname'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('tenant',), name='one_primary_domain_per_tenant')],
            },
        ),
    ]
