# Generated by Django 5.2.12 on 2026-03-28 14:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_menuitem_consume_recipe_on_sale_menuitem_kds_station_and_more'),
        ('pos', '0003_order_discount_amount_order_folio_and_more'),
        ('tenants', '0003_postgres_row_level_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='applied_promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='catalog.promotion'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='kds_station',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='orderline',
            name='kds_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_prep', 'In prep'), ('ready', 'Ready'), ('served', 'Served')], default='pending', max_length=16),
        ),
        migrations.CreateModel(
            name='OfflineQueuedOperation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_mutation_id', models.CharField(help_text='Unique per device/session; prevents duplicate apply.', max_length=128)),
                ('operation_type', models.CharField(help_text='e.g. order_payment, order_create', max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('applied_payment_id', models.UUIDField(blank=True, null=True)),
                ('applied_order_id', models.UUIDField(blank=True, null=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_queue', to='tenants.outlet')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_queue', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'client_mutation_id'), name='uniq_offline_queue_client_mutation_per_tenant')],
            },
        ),
    ]
