# Generated by Django 5.2.12 on 2026-04-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_remove_order_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='modifiers_snapshot',
            field=models.JSONField(blank=True, default=list, help_text='Chosen modifier options at sale time (name + price_delta per option).'),
        ),
    ]
