# Generated by Django 5.2.16 on 2026-09-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_modifiers_and_line_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('mobile_money', 'Mobile money'), ('bank', 'Bank transfer'), ('other', 'Other')], default='cash', max_length=16),
        ),
    ]
