# Generated by Django 5.2.17 on 2026-09-30 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_alter_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='supermarketlinereturn',
            name='refund',
            field=models.OneToOneField(blank=True, help_text='Customer refund recorded with this physical return, if any.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='line_return', to='pos.refund'),
        ),
    ]
