# Generated by Django 5.2.17 on 2026-09-30 12:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_supermarketlinereturn_refund'),
        ('tenants', '0015_tenantsettings_efris_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('code', models.SlugField(max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('receipt_printer', models.CharField(blank=True, max_length=120)),
                ('kitchen_printer', models.CharField(blank=True, max_length=120)),
                ('cash_drawer', models.CharField(blank=True, max_length=80)),
                ('kds_station', models.CharField(blank=True, max_length=64)),
                ('last_seen_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workstations', to='tenants.outlet')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workstations', to='tenants.tenant')),
            ],
            options={
                'ordering': ['outlet__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='posshift',
            name='workstation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='pos.workstation'),
        ),
        migrations.AddConstraint(
            model_name='workstation',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_workstation_code_per_tenant'),
        ),
    ]
