# Generated by Django 5.2.17 on 2026-09-30 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_workstation_rls'),
        ('tenants', '0015_tenantsettings_efris_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='pos.posshift'),
        ),
        migrations.AddField(
            model_name='posshift',
            name='cash_attribution',
            field=models.BooleanField(default=False, help_text='Use explicit payment/refund links; older shifts retain time-window accounting.'),
        ),
        migrations.AlterField(
            model_name='posshift',
            name='cash_attribution',
            field=models.BooleanField(default=True, help_text='Use explicit payment/refund links; older shifts retain time-window accounting.'),
        ),
        migrations.AddField(
            model_name='refund',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='pos.posshift'),
        ),
        migrations.AddConstraint(
            model_name='posshift',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open'), ('workstation__isnull', False)), fields=('workstation',), name='uniq_open_shift_workstation'),
        ),
        migrations.AddConstraint(
            model_name='posshift',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open'), ('workstation__isnull', True)), fields=('outlet',), name='uniq_open_section_shift'),
        ),
    ]
