# Generated by Django 5.2.17 on 2026-09-30 13:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_payment_shift_posshift_cash_attribution_refund_shift_and_more'),
        ('tenants', '0015_tenantsettings_efris_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workstation',
            name='requires_pairing',
            field=models.BooleanField(default=False, help_text='Require administrator-approved browser pairing for staff register operations.'),
        ),
        migrations.CreateModel(
            name='WorkstationPairing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=80)),
                ('token_hash', models.CharField(editable=False, max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, max_length=255)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workstation_pairings_approved', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workstation_pairings_revoked', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workstation_pairings', to='tenants.tenant')),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pairings', to='pos.workstation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
