# Generated by Django 5.2.17 on 2026-09-30 16:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0017_cashdrawermovement_rls'),
        ('tenants', '0015_tenantsettings_efris_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftHandover',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('submitted', 'Awaiting independent count'), ('verified', 'Awaiting manager approval'), ('approved', 'Awaiting next cashier'), ('accepted', 'Accepted')], default='submitted', max_length=16)),
                ('variance_explanation', models.CharField(blank=True, max_length=512)),
                ('verified_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('verification_note', models.CharField(blank=True, max_length=512)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('approval_note', models.CharField(blank=True, max_length=512)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_shift_handovers', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_shift_handovers', to=settings.AUTH_USER_MODEL)),
                ('next_shift', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prior_handover', to='pos.posshift')),
                ('shift', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='handover', to='pos.posshift')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_handovers', to='tenants.tenant')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_shift_handovers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
