from django.urls import include, path

from . import (
    views,
    views_events,
    views_finance,
    views_inventory,
    views_kds,
    views_lodging,
    views_offline,
    views_ops,
    views_promotions,
    views_purchasing,
    views_workstations,
    views_management,
    views_customers,
)

urlpatterns = [
    path("customers/", views_customers.StaffCustomerListView.as_view(), name="staff-customers"),
    path("customers/new/", views_customers.StaffCustomerCreateView.as_view(), name="staff-customer-create"),
    path("customers/<uuid:customer_id>/", views_customers.StaffCustomerDetailView.as_view(), name="staff-customer-detail"),
    path("management/sources/<str:kind>/<uuid:entity_id>/", views_management.StaffManagementSourceView.as_view(), name="staff-management-source"),
    path("management/shifts/<uuid:shift_id>/", views_management.StaffManagementShiftView.as_view(), name="staff-management-shift"),
    path("management/", views_management.StaffManagementView.as_view(), name="staff-management"),
    path("login/", views.StaffLoginView.as_view(), name="staff-login"),
    path("logout/", views.StaffLogoutView.as_view(), name="staff-logout"),
    path("terminal/", views.StaffTerminalView.as_view(), name="staff-terminal"),
    path("terminal/lock/", views.StaffTerminalLockView.as_view(), name="staff-terminal-lock"),
    path("terminal/pin/", views.StaffPinSetupView.as_view(), name="staff-pin-setup"),
    path("pending-approval/", views.StaffPendingApprovalView.as_view(), name="staff-pending-approval"),
    path("setup/prompt/dismiss/", views.StaffSetupPromptDismissView.as_view(), name="staff-setup-prompt-dismiss"),
    path("setup/prompt/resume/", views.StaffSetupPromptResumeView.as_view(), name="staff-setup-prompt-resume"),
    path("select-tenant/", views.StaffSelectTenantView.as_view(), name="staff-select-tenant"),
    path("select-outlet/", views_ops.StaffSelectOutletView.as_view(), name="staff-select-outlet"),
    path("orders/", views_ops.StaffOrdersListView.as_view(), name="staff-orders"),
    path("orders/new/", views_ops.StaffOrderQuickCreateView.as_view(), name="staff-order-quick-create"),
    path("orders/<uuid:order_id>/", views_ops.StaffOrderDetailView.as_view(), name="staff-order-detail"),
    path("orders/<uuid:order_id>/print/", views_ops.StaffOrderPrintView.as_view(), name="staff-order-print"),
    path("pos/workstations/", views_workstations.StaffWorkstationListView.as_view(), name="staff-workstations"),
    path("pos/workstations/<uuid:workstation_id>/browsers/", views_workstations.StaffWorkstationPairView.as_view(), name="staff-workstation-pair"),
    path("pos/workstations/new/", views_workstations.StaffWorkstationEditView.as_view(), name="staff-workstation-create"),
    path("pos/workstations/<uuid:workstation_id>/edit/", views_workstations.StaffWorkstationEditView.as_view(), name="staff-workstation-edit"),
    path("pos/shifts/", views_ops.StaffPosShiftListView.as_view(), name="staff-pos-shifts"),
    path("tables/new/", views_ops.StaffTableCreateView.as_view(), name="staff-table-create"),
    path(
        "tables/<uuid:table_id>/edit/",
        views_ops.StaffTableUpdateView.as_view(),
        name="staff-table-edit",
    ),
    path("tables/", views_ops.StaffTablesListView.as_view(), name="staff-tables"),
    path("kitchen/", views_kds.StaffKdsQueueView.as_view(), name="staff-kds"),
    path("menu/", views_ops.StaffMenuListView.as_view(), name="staff-menu"),
    path("promotions/new/", views_promotions.StaffPromotionCreateView.as_view(), name="staff-promotion-create"),
    path(
        "promotions/<uuid:promotion_id>/edit/",
        views_promotions.StaffPromotionUpdateView.as_view(),
        name="staff-promotion-edit",
    ),
    path(
        "promotions/<uuid:promotion_id>/",
        views_promotions.StaffPromotionDetailView.as_view(),
        name="staff-promotion-detail",
    ),
    path("promotions/", views_promotions.StaffPromotionListView.as_view(), name="staff-promotions"),
    path("reports/sales/", views_ops.StaffSalesSummaryView.as_view(), name="staff-sales"),
    path("finance/", views_finance.StaffFinanceEntryListView.as_view(), name="staff-finance-entries"),
    path("finance/new/", views_finance.StaffFinanceEntryCreateView.as_view(), name="staff-finance-entry-create"),
    path(
        "finance/categories/new/",
        views_finance.StaffFinanceCategoryCreateView.as_view(),
        name="staff-finance-categories-new",
    ),
    path(
        "pos/offline-queue/",
        views_offline.StaffOfflineQueueListView.as_view(),
        name="staff-offline-queue",
    ),
    path(
        "inventory/movements/new/",
        views_inventory.StaffStockMovementCreateView.as_view(),
        name="staff-inventory-movement-create",
    ),
    path(
        "inventory/movements/upload/",
        views_inventory.StaffStockMovementUploadView.as_view(),
        name="staff-inventory-movement-upload",
    ),
    path(
        "inventory/movements/upload/template.csv",
        views_inventory.StaffStockMovementUploadTemplateCsvView.as_view(),
        name="staff-inventory-movement-upload-template",
    ),
    path(
        "inventory/movements/upload/errors.csv",
        views_inventory.StaffStockMovementUploadErrorCsvView.as_view(),
        name="staff-inventory-movement-upload-errors",
    ),
    path("inventory/movements/", views_inventory.StaffStockMovementListView.as_view(), name="staff-inventory-movements"),
    path("inventory/transfer/", views_inventory.StaffStockTransferView.as_view(), name="staff-inventory-transfer"),
    path(
        "inventory/counts/new/",
        views_inventory.StaffStockCountCreateView.as_view(),
        name="staff-inventory-count-create",
    ),
    path(
        "inventory/counts/<uuid:session_id>/",
        views_inventory.StaffStockCountDetailView.as_view(),
        name="staff-inventory-count-detail",
    ),
    path("inventory/counts/", views_inventory.StaffStockCountListView.as_view(), name="staff-inventory-counts"),
    path("inventory/", views_inventory.StaffStockBalanceListView.as_view(), name="staff-inventory-balances"),
    path(
        "purchasing/suppliers/new/",
        views_purchasing.StaffSupplierCreateView.as_view(),
        name="staff-purchasing-supplier-create",
    ),
    path(
        "purchasing/suppliers/<uuid:supplier_id>/edit/",
        views_purchasing.StaffSupplierUpdateView.as_view(),
        name="staff-purchasing-supplier-edit",
    ),
    path("purchasing/suppliers/", views_purchasing.StaffSupplierListView.as_view(), name="staff-purchasing-suppliers"),
    path(
        "purchasing/purchase-orders/new/",
        views_purchasing.StaffPurchaseOrderCreateView.as_view(),
        name="staff-purchasing-order-create",
    ),
    path(
        "purchasing/purchase-orders/<uuid:po_id>/",
        views_purchasing.StaffPurchaseOrderDetailView.as_view(),
        name="staff-purchasing-order-detail",
    ),
    path(
        "purchasing/purchase-orders/",
        views_purchasing.StaffPurchaseOrderListView.as_view(),
        name="staff-purchasing-orders",
    ),
    path("lodging/select-site/", views_lodging.StaffSelectSiteView.as_view(), name="staff-select-site"),
    path(
        "lodging/reservations/new/",
        views_lodging.StaffReservationCreateView.as_view(),
        name="staff-lodging-reservation-create",
    ),
    path(
        "lodging/reservations/<uuid:reservation_id>/",
        views_lodging.StaffReservationDetailView.as_view(),
        name="staff-lodging-reservation-detail",
    ),
    path(
        "lodging/availability/",
        views_lodging.StaffLodgingAvailabilityView.as_view(),
        name="staff-lodging-availability",
    ),
    path(
        "lodging/tape-chart/",
        views_lodging.StaffLodgingTapeChartView.as_view(),
        name="staff-lodging-tape",
    ),
    path("lodging/reservations/", views_lodging.StaffReservationsListView.as_view(), name="staff-lodging-reservations"),
    path(
        "lodging/folios/<uuid:folio_id>/",
        views_lodging.StaffFolioDetailView.as_view(),
        name="staff-lodging-folio-detail",
    ),
    path("lodging/folios/", views_lodging.StaffFolioListView.as_view(), name="staff-lodging-folios"),
    path("lodging/rooms/", views_lodging.StaffRoomsListView.as_view(), name="staff-lodging-rooms"),
    path(
        "lodging/housekeeping/",
        views_lodging.StaffHousekeepingBoardView.as_view(),
        name="staff-lodging-housekeeping",
    ),
    path(
        "lodging/maintenance/",
        views_lodging.StaffRoomMaintenanceView.as_view(),
        name="staff-lodging-maintenance",
    ),
    path(
        "lodging/room-types/",
        views_lodging.StaffLodgingRoomTypesListView.as_view(),
        name="staff-lodging-room-types",
    ),
    path(
        "events/spaces/new/",
        views_events.StaffEventSpaceCreateView.as_view(),
        name="staff-events-space-create",
    ),
    path(
        "events/spaces/<uuid:space_id>/edit/",
        views_events.StaffEventSpaceUpdateView.as_view(),
        name="staff-events-space-edit",
    ),
    path("events/spaces/", views_events.StaffEventSpaceListView.as_view(), name="staff-events-spaces"),
    path(
        "events/bookings/new/",
        views_events.StaffEventBookingCreateView.as_view(),
        name="staff-events-booking-create",
    ),
    path(
        "events/bookings/<uuid:booking_id>/",
        views_events.StaffEventBookingUpdateView.as_view(),
        name="staff-events-booking-detail",
    ),
    path("events/bookings/", views_events.StaffEventBookingListView.as_view(), name="staff-events-bookings"),
    path(
        "events/calendar/",
        views_events.StaffEventCalendarView.as_view(),
        name="staff-events-calendar",
    ),
    path("settings/", include("apps.staff.urls_workspace")),
    path("", views.StaffDashboardView.as_view(), name="staff-dashboard"),
]
