"""Staff Django forms (split by domain; import from ``apps.staff.forms`` as before)."""

from .auth import StaffLoginForm, StaffPinSetupForm, StaffTerminalUnlockForm
from .events import StaffEventBookingForm, StaffEventSpaceForm
from .finance import StaffCashbookEntryForm, StaffFinanceCategoryForm
from .inventory import (
    StaffQuickTrackedMenuItemForm,
    StaffStockCountSessionForm,
    StaffStockMovementForm,
    StaffStockMovementUploadForm,
    StaffStockTransferForm,
)
from .lodging import StaffFolioManualLineForm, StaffFolioPaymentForm, StaffReservationForm, StaffRoomMaintenanceForm
from .pos_orders import (
    StaffOrderAdjustLineQuantityForm,
    StaffOrderAddLineForm,
    StaffOrderAddServiceForm,
    StaffOrderApplyPromotionForm,
    StaffOrderHoldForm,
    StaffOrderLineDiscountForm,
    StaffOrderReadyHandoffForm,
    StaffOrderLineReturnForm,
    StaffOrderPaymentForm,
    StaffOrderSetFolioForm,
    StaffOrderRefundForm,
    StaffRetailLineRefundForm,
    StaffOrderScanAddForm,
    StaffPosShiftCloseForm,
    StaffPosShiftOpenForm,
    StaffOrderVoidOrderForm,
    StaffOrderVoidLineForm,
    StaffTableForm,
)
from .promotions import StaffPromotionForm
from .purchasing import StaffPOHeaderForm, StaffSupplierForm
from .workspace_forms import (
    StaffEfrisSettingsForm,
    StaffIntegrationLinkForm,
    StaffMembershipBulkActionForm,
    StaffMembershipManageForm,
    StaffTeamInviteForm,
    StaffTenantBrandingForm,
    StaffTenantModulesForm,
    StaffWorkerCreateForm,
)

__all__ = [
    "StaffCashbookEntryForm",
    "StaffEfrisSettingsForm",
    "StaffEventBookingForm",
    "StaffEventSpaceForm",
    "StaffFinanceCategoryForm",
    "StaffFolioManualLineForm",
    "StaffFolioPaymentForm",
    "StaffRoomMaintenanceForm",
    "StaffIntegrationLinkForm",
    "StaffMembershipBulkActionForm",
    "StaffMembershipManageForm",
    "StaffLoginForm",
    "StaffPinSetupForm",
    "StaffTerminalUnlockForm",
    "StaffOrderAdjustLineQuantityForm",
    "StaffOrderAddLineForm",
    "StaffOrderAddServiceForm",
    "StaffOrderApplyPromotionForm",
    "StaffOrderHoldForm",
    "StaffOrderLineDiscountForm",
    "StaffOrderReadyHandoffForm",
    "StaffOrderLineReturnForm",
    "StaffOrderPaymentForm",
    "StaffOrderSetFolioForm",
    "StaffPosShiftCloseForm",
    "StaffPosShiftOpenForm",
    "StaffOrderRefundForm",
    "StaffRetailLineRefundForm",
    "StaffOrderScanAddForm",
    "StaffOrderVoidOrderForm",
    "StaffOrderVoidLineForm",
    "StaffPOHeaderForm",
    "StaffPromotionForm",
    "StaffQuickTrackedMenuItemForm",
    "StaffReservationForm",
    "StaffStockCountSessionForm",
    "StaffStockMovementForm",
    "StaffStockMovementUploadForm",
    "StaffStockTransferForm",
    "StaffSupplierForm",
    "StaffTableForm",
    "StaffTeamInviteForm",
    "StaffTenantBrandingForm",
    "StaffTenantModulesForm",
    "StaffWorkerCreateForm",
]
